"""Adicionar funcionalidade de calculo de preços

Revision ID: 4976bfc1e6d3
Revises: 4ff74f19cb4a
Create Date: 2025-09-27 13:25:57.167325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4976bfc1e6d3'
down_revision: Union[str, Sequence[str], None] = '4ff74f19cb4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
